### ISSUE TITLE
Recommendation: Add Compiled Release + CIA Build

### ISSUE THREAD

**Issue by GabrielRRussell** [UnsureSherlock/checkers3ds#1]
Your Filedropper link is dead, and you don't have compiled versions in a release or code, so you should probably repackage it. You can just click "releases" at the top and add a new one with all of the binaries. 

You can use MakeRom to make a CIA build too.

**Comment by Kevoot** [comment]
This was more of a quick pet project, and frankly the quality of code present throughout is pretty subpar compared to my current skill set. I might get around to rewriting it, but as of now I have no plans of fixing/recompiling.
